# Generated by Django 5.0.6 on 2024-07-04 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_cartmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsCategory',
            new_name='NewsCategoryModel',
        ),
        migrations.RenameModel(
            old_name='News',
            new_name='NewsModel',
        ),
    ]
